const translations = {
  en: {
    'tab.accounts':        'Accounts',
    'tab.cards':           'Cards',
    'tab.offers':          'Offers',
    'tab.menu':            'Menu',
    'nav.card-details':           'Card details',
    'nav.safety-settings':        'Safety settings',
    'nav.new-payment':            'New payment',
    'nav.partners':               'Partners',
    'nav.account-details':        'Account details',
    'nav.authorization':          'Authorization',
    'nav.account-transactions':   'Account transactions',
    'nav.card-transactions':      'Card transactions',
    'nav.transaction-details':    'Transaction details',
    'nav.select-client':          'Select client',
    'home.balance':        'Balance',
    'home.available':      'Available balance',
    'home.last-tx':        'Last transactions',
    'home.see-all':        'See all',
    'card.outstanding':    'Outstanding amount',
    'card.settlement':     'Next settlement amount',
    'card.nickname':       'Nickname',
    'card.safety':         'Safety',
    'card.settings':       'Card settings',
    'card.limit':          'Monthly limit',
    'card.repayment':      'Card repayment',
    'card.number':         'Card number',
    'card.valid-thru':     'Valid thru',
    'safety.block':        'Block card temporarily',
    'safety.online':       'Online shopping',
    'safety.atm':          'ATM withdrawals',
    'safety.abroad':       'Use outside Slovenia',
    'action.details':      'Details',
    'action.transactions': 'Transactions',
    'action.safety':       'Safety settings',
    'pay.pay-from':        'Pay from',
    'pay.pay-to':          'Pay to',
    'pay.payment':         'Payment',
    'pay.step1':           '1. Prepare',
    'pay.step2':           '2. Review',
    'pay.step3':           '3. Sent',
    'pay.debit-account':   'Debit account',
    'pay.account':         'Account',
    'pay.name':            'Name',
    'pay.partners':        'Partners',
    'pay.check-account':   'Check account',
    'pay.instant':         'Instant',
    'pay.urgent':          'Urgent',
    'pay.exec-date':       'Execution date',
    'pay.amount':          'Amount (EUR)',
    'pay.creditor-ref':    'Creditor reference',
    'pay.purpose':         'Purpose code',
    'pay.details':         'Details',
    'pay.next':            'Next',
    'pay.pay':             'Pay',
    'pay.new':             'New payment',
    'pay.save-quick':      'Save as quick pay',
    'pay.cancel':          'Cancel payment',
    'pay.success':         'Payment was successfully executed and funds were transferred to creditor account.',
    'pay.sent-success':    'Payment was successfully executed and funds were transferred to creditor account.',
    'partners.search':     'Search partners…',
    'acc.main':            'Main account',
    'acc.nickname':        'Nickname',
    'acc.package':         'Package',
    'acc.overdraft':       'Overdraft limit',
    'acc.info-title':      'Account info',
    'acc.holder':          'Account holder',
    'acc.commercial':      'Commercial name',
    'acc.commercial-val':  'Transaction account',
    'acc.status':          'Status',
    'acc.status-val':      'Active',
    'acc.balance-title':   'Balance',
    'acc.balance':         'Balance',
    'acc.available':       'Available balance',
    'menu.payments':       'Payments',
    'menu.new-payments':   'New payments',
    'menu.quick-pay':      'Quick pay',
    'menu.photo-pay':      'Photo pay',
    'menu.flik':           'Flik',
    'menu.sent':           'Sent payments',
    'menu.standing':       'Standing orders',
    'menu.partners':       'Partners',
    'menu.e-invoices':     'E-invoices',
    'menu.verify':         'Verify online payments',
    'menu.products':       'Products',
    'menu.accounts':       'Accounts',
    'menu.cards':          'Cards',
    'menu.statements':     'Statements & documents',
    'stmt.filter-by-type': 'Filter by type',
    'stmt.tag.trr':        'TRR',
    'stmt.tag.cards':      'Cards',
    'stmt.tag.cash':       'Cash',
    'stmt.tag.loans':      'Loans',
    'stmt.tag.savings':    'Savings',
    'stmt.tag.other':      'Other',
    'stmt.cat.trr':        'Transaction account',
    'stmt.cat.cards':      'Cards',
    'stmt.cat.cash':       'Cash / cash operations',
    'stmt.cat.loans':      'Loans',
    'stmt.cat.savings':    'Savings and investments',
    'stmt.cat.other':      'Other',
    'sf.title':            'Filter',
    'sf.date-from':        'Date from',
    'sf.date-to':          'Date to',
    'sf.subtype':          'Document subtype',
    'sf.all-types':        'All types',
    'sf.statements':       'Statements',
    'sf.contracts':        'Contracts',
    'sf.other':            'Other',
    'sf.subject':          'Subject / name of document',
    'sf.btn':              'Filter',
    'common.change':       'change',
    'common.cancel':       'Cancel',
    'common.save':         'Save',
    'common.no':           'No',
    'common.yes':          'Yes',
    'dialog.change-nick':  'Change nickname',
    'dialog.nick-ph':      'Nickname',
    'dialog.save-quick':   'Save as quick payment',
    'dialog.pay-name-ph':  'Payment name',
    'dialog.cancel-pay':   'Are you sure you want to cancel this payment?',
    'error.mandatory':     'Mandatory field',
    'purpose.OTHR': 'OTHR - Other payment purpose',
    'purpose.SALA': 'SALA - Salary payment',
    'purpose.RENT': 'RENT - Rent payment',
    'purpose.UTIL': 'UTIL - Utility bill payment',
    'purpose.TAXS': 'TAXS - Tax payment',
    'purpose.LOAN': 'LOAN - Loan repayment',
    'purpose.INSUR': 'INSUR - Insurance premium',
    'purpose.MEDI': 'MEDI - Medical services',
    'purpose.EDUC': 'EDUC - Education fees',
    'purpose.TRVL': 'TRVL - Travel expenses',
    'purpose.SUPP': 'SUPP - Supplier payment',
    'purpose.GDDS': 'GDDS - Purchase of goods',
    'purpose.SVCS': 'SVCS - Purchase of services',
    'purpose.COMM': 'COMM - Commission payment',
    'purpose.DIVI': 'DIVI - Dividend payment',
    'purpose.CHAR': 'CHAR - Charitable payment',
    'purpose.PENS': 'PENS - Pension payment',
    'purpose.INVS': 'INVS - Investment payment',
    'purpose.GOVT': 'GOVT - Government payment',
    'purpose.RCPT': 'RCPT - Receipt of funds',
    'purpose.INTC': 'INTC - Intra-company payment',
    'banner.home-title':   'Account limit',
    'banner.home-desc':    'You can change your account limit directly inside our app.',
    'banner.offer1-title': 'Virtual card',
    'banner.offer1-desc':  'Create a virtual card and use it for online payments instantly.',
    'banner.offer2-title': 'Block your card',
    'banner.offer2-desc':  'Temporarily block your card directly from the app at any time.',
  },
  sl: {
    'tab.accounts':        'Računi',
    'tab.cards':           'Kartice',
    'tab.offers':          'Ponudbe',
    'tab.menu':            'Meni',
    'nav.card-details':           'Podrobnosti kartice',
    'nav.safety-settings':        'Varnostne nastavitve',
    'nav.new-payment':            'Novo plačilo',
    'nav.partners':               'Partnerji',
    'nav.account-details':        'Podrobnosti računa',
    'nav.authorization':          'Avtorizacija',
    'nav.account-transactions':   'Transakcije računa',
    'nav.card-transactions':      'Transakcije kartice',
    'nav.transaction-details':    'Podrobnosti transakcije',
    'nav.select-client':          'Izbira stranke',
    'home.balance':        'Stanje',
    'home.available':      'Razpoložljivo stanje',
    'home.last-tx':        'Zadnje transakcije',
    'home.see-all':        'Prikaži vse',
    'card.outstanding':    'Neporavnan znesek',
    'card.settlement':     'Naslednji obračun',
    'card.nickname':       'Vzdevek',
    'card.safety':         'Varnost',
    'card.settings':       'Nastavitve kartice',
    'card.limit':          'Mesečna omejitev',
    'card.repayment':      'Odplačilo kartice',
    'card.number':         'Številka kartice',
    'card.valid-thru':     'Veljavna do',
    'safety.block':        'Začasno blokiraj kartico',
    'safety.online':       'Spletno nakupovanje',
    'safety.atm':          'Dvigi na bankomatih',
    'safety.abroad':       'Uporaba zunaj Slovenije',
    'action.details':      'Podrobnosti',
    'action.transactions': 'Transakcije',
    'action.safety':       'Varnostne nastavitve',
    'pay.pay-from':        'Plačaj z',
    'pay.pay-to':          'Plačaj na',
    'pay.payment':         'Plačilo',
    'pay.step1':           '1. Priprava',
    'pay.step2':           '2. Pregled',
    'pay.step3':           '3. Poslano',
    'pay.debit-account':   'Bremenilni račun',
    'pay.account':         'Račun',
    'pay.name':            'Ime',
    'pay.partners':        'Partnerji',
    'pay.check-account':   'Preveri račun',
    'pay.instant':         'Takojšnje',
    'pay.urgent':          'Nujno',
    'pay.exec-date':       'Datum izvršitve',
    'pay.amount':          'Znesek (EUR)',
    'pay.creditor-ref':    'Referenca prejemnika',
    'pay.purpose':         'Namen plačila',
    'pay.details':         'Opis',
    'pay.next':            'Naprej',
    'pay.pay':             'Plačaj',
    'pay.new':             'Novo plačilo',
    'pay.save-quick':      'Shrani kot hitro plačilo',
    'pay.cancel':          'Prekliči plačilo',
    'pay.success':         'Plačilo je bilo uspešno izvedeno in sredstva so bila prenesena na račun upnika.',
    'pay.sent-success':    'Plačilo je bilo uspešno izvedeno in sredstva so bila prenesena na račun upnika.',
    'partners.search':     'Išči partnerje…',
    'acc.main':            'Glavni račun',
    'acc.nickname':        'Vzdevek',
    'acc.package':         'Paket',
    'acc.overdraft':       'Limit prekoračitve',
    'acc.info-title':      'Informacije o računu',
    'acc.holder':          'Imetnik računa',
    'acc.commercial':      'Komercialno ime',
    'acc.commercial-val':  'Transakcijski račun',
    'acc.status':          'Status',
    'acc.status-val':      'Aktivno',
    'acc.balance-title':   'Stanje',
    'acc.balance':         'Stanje',
    'acc.available':       'Razpoložljivo stanje',
    'menu.payments':       'Plačila',
    'menu.new-payments':   'Nova plačila',
    'menu.quick-pay':      'Hitra plačila',
    'menu.photo-pay':      'Foto plačilo',
    'menu.flik':           'Flik',
    'menu.sent':           'Poslana plačila',
    'menu.standing':       'Trajni nalogi',
    'menu.partners':       'Partnerji',
    'menu.e-invoices':     'E-računi',
    'menu.verify':         'Preveri spletna plačila',
    'menu.products':       'Produkti',
    'menu.accounts':       'Računi',
    'menu.cards':          'Kartice',
    'menu.statements':     'Izpiski in dokumenti',
    'stmt.filter-by-type': 'Filtriraj po vrsti',
    'stmt.tag.trr':        'TRR',
    'stmt.tag.cards':      'Kartice',
    'stmt.tag.cash':       'Blagajna',
    'stmt.tag.loans':      'Krediti',
    'stmt.tag.savings':    'Varčevanje',
    'stmt.tag.other':      'Ostalo',
    'stmt.cat.trr':        'Transakcijski račun',
    'stmt.cat.cards':      'Kartice',
    'stmt.cat.cash':       'Blagajna / gotovinsko poslovanje',
    'stmt.cat.loans':      'Krediti',
    'stmt.cat.savings':    'Varčevanje in naložbe',
    'stmt.cat.other':      'Ostalo',
    'sf.title':            'Filter',
    'sf.date-from':        'Datum od',
    'sf.date-to':          'Datum do',
    'sf.subtype':          'Podvrsta dokumenta',
    'sf.all-types':        'Vse vrste',
    'sf.statements':       'Izpiski',
    'sf.contracts':        'Pogodbe',
    'sf.other':            'Ostalo',
    'sf.subject':          'Zadeva / ime dokumenta',
    'sf.btn':              'Filtriraj',
    'common.change':       'spremeni',
    'common.cancel':       'Prekliči',
    'common.save':         'Shrani',
    'common.no':           'Ne',
    'common.yes':          'Da',
    'dialog.change-nick':  'Sprememba vzdevka',
    'dialog.nick-ph':      'Vzdevek',
    'dialog.save-quick':   'Shrani kot hitro plačilo',
    'dialog.pay-name-ph':  'Ime plačila',
    'dialog.cancel-pay':   'Ste prepričani, da želite preklicati to plačilo?',
    'error.mandatory':     'Obvezno polje',
    'purpose.OTHR': 'OTHR - Drug namen plačila',
    'purpose.SALA': 'SALA - Plačilo plače',
    'purpose.RENT': 'RENT - Plačilo najemnine',
    'purpose.UTIL': 'UTIL - Plačilo režijskih stroškov',
    'purpose.TAXS': 'TAXS - Plačilo davkov',
    'purpose.LOAN': 'LOAN - Odplačilo posojila',
    'purpose.INSUR': 'INSUR - Zavarovalna premija',
    'purpose.MEDI': 'MEDI - Medicinske storitve',
    'purpose.EDUC': 'EDUC - Šolnine',
    'purpose.TRVL': 'TRVL - Potni stroški',
    'purpose.SUPP': 'SUPP - Plačilo dobavitelju',
    'purpose.GDDS': 'GDDS - Nakup blaga',
    'purpose.SVCS': 'SVCS - Nakup storitev',
    'purpose.COMM': 'COMM - Plačilo provizije',
    'purpose.DIVI': 'DIVI - Izplačilo dividend',
    'purpose.CHAR': 'CHAR - Humanitarno plačilo',
    'purpose.PENS': 'PENS - Pokojnina',
    'purpose.INVS': 'INVS - Naložbeno plačilo',
    'purpose.GOVT': 'GOVT - Državno plačilo',
    'purpose.RCPT': 'RCPT - Prejem sredstev',
    'purpose.INTC': 'INTC - Plačilo znotraj podjetja',
    'banner.home-title':   'Limit računa',
    'banner.home-desc':    'Limit svojega računa lahko spremenite neposredno v naši aplikaciji.',
    'banner.offer1-title': 'Virtualna kartica',
    'banner.offer1-desc':  'Ustvarite virtualno kartico in jo takoj uporabite za spletna plačila.',
    'banner.offer2-title': 'Blokirajte svojo kartico',
    'banner.offer2-desc':  'Svojo kartico začasno blokirajte neposredno v aplikaciji kadar koli.',
  },
};

const purposeCodes = ['OTHR','SALA','RENT','UTIL','TAXS','LOAN','INSUR','MEDI','EDUC','TRVL','SUPP','GDDS','SVCS','COMM','DIVI','CHAR','PENS','INVS','GOVT','RCPT','INTC'];

let appData = {

  accounts: [
    {
      label: 'My account',
      iban: 'SI56 7834 4562 3313 351',
      available: '10.700,00',
      current: '8.500,00',
      package: 'Medium package',
      packageUsage: [
        { label: 'ATM withdrawals', value: '1/3' },
        { label: 'Transactions',    value: '2/5' },
      ],
      transactions: [
        { date: '31.07.2026', name: 'PSN Store',   amount: '-62,80',    positive: false },
        { date: '27.07.2026', name: 'Online Shop', amount: '-30,00',    positive: false },
        { date: '15.07.2026', name: 'Halcom d.d.', amount: '1.200,00', positive: true  },
      ],
      actions: ['photopay', 'new-pay', 'quick-pay', 'auth'],
    },
    {
      label: 'Savings account',
      iban: 'SI56 6100 0002 7812 456',
      available: '3.240,00',
      current: '3.100,00',
      package: 'Basic package',
      packageUsage: [
        { label: 'ATM withdrawals', value: '0/2' },
        { label: 'Transactions',    value: '1/3' },
      ],
      transactions: [
        { date: '28.07.2026', name: 'Amazon',    amount: '-89,99', positive: false },
        { date: '20.07.2026', name: 'Mercator',  amount: '-24,50', positive: false },
      ],
      actions: ['photopay', 'new-pay'],
    },
  ],

  actionDefs: {
    'photopay':       { icon: 'assets/photopay.svg',  label: 'Photo pay'      },
    'new-pay':        { icon: 'assets/new-pay.svg',   label: 'New payment'    },
    'quick-pay':      { icon: 'assets/quick-pay.svg', label: 'Quick pay'      },
    'auth':           { icon: 'assets/flik.svg',       label: 'Flik'           },
    'authorization':  { icon: 'assets/auth.svg',       label: 'Authorization'  },
  },

  cards: [
    {
      name:           'Mastercard - John Doe',
      type:           'credit',
      number:         '1234 **** **** 4313',
      validThru:      '09/27',
      outstanding:    '400,00',
      settlement:     '200,00',
      settlementDate: 'will be settled on 18.12.2026',
      limit:          '600,00 EUR',
    },
    {
      name:           'Mastercard - Jane Smith',
      type:           'debit',
      number:         '3513 **** **** 1465',
      validThru:      '05/31',
      outstanding:    '0,00',
      settlement:     '0,00',
      settlementDate: 'will be settled on 18.12.2026',
      limit:          '500,00 EUR',
    },
  ],

  banners: {
    home: {
      title: 'Account limit',
      desc:  'You can change your account limit directly inside our app.',
    },
    offers: [
      { title: 'Virtual card',    desc: 'Create a virtual card and use it for online payments instantly.' },
      { title: 'Block your card', desc: 'Temporarily block your card directly from the app at any time.'  },
    ],
  },

};

const companyData = {

  accounts: [
    {
      label: 'Company',
      iban: 'SI56 0292 0000 5531 892',
      available: '284.500,00',
      current: '276.300,00',
      package: 'Business package',
      packageUsage: [
        { label: 'Transactions',    value: '14/50' },
        { label: 'Wire transfers',  value: '3/10'  },
      ],
      transactions: [
        { date: '31.07.2026', name: 'Supplier A d.o.o.', amount: '-12.400,00', positive: false },
        { date: '29.07.2026', name: 'Client B d.d.',     amount: '+45.000,00', positive: true  },
        { date: '22.07.2026', name: 'Office rent',       amount: '-2.800,00',  positive: false },
      ],
      balanceLabel: 'Available balance',
      currentLabel: 'Current balance',
      actions: ['photopay', 'new-pay', 'quick-pay', 'authorization'],
    },
    {
      label: 'Reserve account',
      iban: 'SI56 0292 0000 6612 774',
      available: '95.000,00',
      current: '91.200,00',
      balanceLabel: 'Available balance',
      currentLabel: 'Current balance',
      package: 'Business package',
      packageUsage: [
        { label: 'Transactions',   value: '2/50' },
        { label: 'Wire transfers', value: '0/10' },
      ],
      transactions: [
        { date: '01.07.2026', name: 'Transfer in', amount: '+50.000,00', positive: true },
      ],
      actions: ['new-pay'],
    },
  ],

  actionDefs: appData.actionDefs,

  cards: [
    {
      name:           'Mastercard - Company d.d.',
      type:           'credit',
      number:         '5512 **** **** 8823',
      validThru:      '11/28',
      outstanding:    '8.200,00',
      settlement:     '4.100,00',
      settlementDate: 'will be settled on 18.12.2026',
      limit:          '20.000,00 EUR',
    },
  ],

  banners: {
    home: {
      title: 'Business overdraft',
      desc:  'Activate a business overdraft facility and keep your operations running smoothly.',
    },
    offers: [
      { title: 'Business card', desc: 'Issue additional business cards for your employees instantly.' },
      { title: 'FX payments',   desc: 'Send international payments in foreign currencies at competitive rates.' },
    ],
  },

};
